# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExermoteMachineLearningEngine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google/SignIn'
  pod 'NVActivityIndicatorView'

  target 'ExermoteMachineLearningEngineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExermoteMachineLearningEngineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
