# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exermote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'KDCircularProgress'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka', :branch => 'swift3.2'

  target 'ExermoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExermoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
